Av/create product
ava-techwizard/inventory-pro pull request #1
Opened 2023-04-24 12:44 UTC by anujSingh-A-writer

JIRA: https://anujsingh.atlassian.net/browse/NEX-22

2023-04-25 12:44 UTC, Comaecod requested changes
Few comments

2023-04-25 12:44 UTC, Comaecod commented on components/form/Form.tsx
Delete this file.

2023-04-25 12:44 UTC, Comaecod commented on pages/products/create.tsx
> +    await axios.post(CREATE_PRODUCT, productDetails).then(() => {
Create a hook for API requests.

2023-04-26 03:34 UTC, anujSingh-A-writer commented on components/form/Form.tsx
Deleted

2023-04-26 04:55 UTC, anujSingh-A-writer commented on pages/products/create.tsx
> +    await axios.post(CREATE_PRODUCT, productDetails).then(() => {
Learning SWR, a react hook.

2023-04-26 05:13 UTC, Comaecod approved these changes
Looks Good!

2023-04-26 05:13 UTC, merged